version: '3.3'

services:
   db:
     image: postgres:12.2
     volumes:
       - db_tsadmin_posgres:/var/lib/postgresql/data
     restart: always
     ports:
       - 5432:5432
     environment:
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
       POSTGRES_DB: tsadmindev

volumes:
    db_tsadmin_posgres: {}
