version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      # MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'user'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'password'
      # Password for root access
      # MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql_volume:/var/lib/mysql
# Names our volume
volumes:
  my-db:

# docker run -it --rm --network host mysql mysql -h 127.0.0.1 -u root